### ISSUE TITLE
Bug: every component should be able to be hidden by attribute

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#202]
### Summary

The following should be available on every component.

```scss
:host([hidden]) {
  display: none;
}
```

### Actual Behavior

its not on every component

### Expected Behavior

Every component can be hidden with the `hidden` attribute

### Relevant Info 

Can we put this in the common SCSS file?
