### ISSUE TITLE
Bug: Global styles have classnames that are not scoped to `calcite-app-components`

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#734]
### Summary

The following SCSS files have classnames that are vague and not scoped to calcite-app-components:

#### `_base.scss`

```scss
header {
  margin: 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  color: var(--calcite-app-foreground);
  fill: var(--calcite-app-foreground);
}

.heading {
  padding: 0;
  margin: 0;
}

.header .heading {
  flex: 1 0 auto;
  padding: var(--calcite-app-cap-spacing-half) var(--calcite-app-side-spacing-half);
}
```

#### `_type.scss`

```scss
.heading {
  font-weight: var(--calcite-app-font-weight-demi);
}

h1.heading {
  font-size: var(--calcite-app-font-size-3);
}

h2.heading {
  font-size: var(--calcite-app-font-size-2);
}

h3.heading {
  font-size: var(--calcite-app-font-size-1);
}
h4.heading,
h5.heading {
  font-size: var(--calcite-app-font-size-0);
}
```

#### Root setting default font sizes

The following CSS is being set for anywhere that includes the global css file. We should probably not be setting these for any project that uses our components.

```scss
  font-family: var(--calcite-app-font-family);
  font-size: var(--calcite-app-base-font-size);
  line-height: var(--calcite-app-line-height);
```

### Expected Behavior

These styles should be scoped so that someone else doesn't conflict with the names of these styles. Styles such as `heading` are easy to conflict with.

### Relevant Info 

The built global styles are not scoped to our components in any way.

@jcfranco can you confirm this?
