### ISSUE TITLE
Enhancement: calcite-flow-item needs an onscroll event 

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#841]
### Description
My component needs to close a popover if the user scrolls the content of a flow-item.
The document.click event does not catch this event and neither does the onscroll event directly on the flow-item or my content div of the flow-item.

**Comment by mitc7862** [comment]
@AdelheidF Would it close anytime the user scrolls or only when the position of the popover is off-screen?

**Comment by driskull** [comment]
@AdelheidF is the Popover inside of the content that is scrolling? If so, it should be able to hide it.

Another option would be using these attributes that get added to the Popover...

- data-popper-reference-hidden: This attribute gets applied to the popper when the reference element is fully clipped and hidden from view, which causes the popper to appear to be attached to nothing.
- data-popper-escaped: This attribute gets applied when the popper escapes the reference element's boundary (and so it appears detached).

```scss
/* Hide the popper when the reference is hidden */
calcite-popover[data-popper-reference-hidden] {
  visibility: hidden;
  pointer-events: none;
}
```
